baseurl: 'https://grow-ai-like-a-child.github.io/'
permalink: pretty
title: 'GrowAI'

logo:
  # mobile: "images/logo/logo.jpeg"
  # mobile_height: "32px"
  # mobile_width: "32px"
  # desktop: "images/logo/logo.jpeg"
  # desktop_height: "32px"
  # desktop_width: "120px"

home: 
  limit_services: 6

collections:
  services:
    output: true
    sort_by: weight
  projects:
    output: true
    sort_by: weight
  team:
    output: true

defaults:
  - scope:
      path: "_projects"
      type: "services"
    values:
      layout: "service"
  - scope:
      path: "_services"
      type: "services"
    values:
      layout: "service"
  - scope:
      path: ""
      type: "team"
    values:
      layout: "team"

sass:
  style: compressed # possible values: nested expanded compact compressed

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false


# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

plugins:
  - jekyll-environment-variables

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.md
  - LICENSE
  - README.md
